### PR TITLE
change stuct.h to micropython.h

### PR DESCRIPTION
**Pull request by grugnoymeme**

### CODE REVIEW

**Comment by zap8600** [comment]
This isn't possible, no need changing anything.

**Comment by grugnoymeme** [comment]
no bc in the micropython.c file you have this line:
#include "micropython.h"
and when u try to build it, it not find the file micropython.h, so change the name, or change the line to:
#include "struct.h"
now i built it

**Comment by grugnoymeme** [comment]
it built it correct, but crashes opening

**Comment by zap8600** [comment]
Micropython uses too much RAM and crashes the system.

**Comment by grugnoymeme** [comment]
yes i thought so...

**Comment by grugnoymeme** [comment]
anyway i think  should be solved the things of struct.h, cause if u leave it like this it give back an error.. let me know

**Comment by grugnoymeme** [comment]
u included "micropython.h" in the main file (micropython.c), but that file's name is struct.h, so you need to change the name from struct.h to micropython.h or change the include in micropython.c from #include "micropython.h" to #include "struct.h".
that's what i mean... try to build now and you'll recive an fbt error

**Pull request closed without merging**
